In [1]:
import pandas as pd
import os
import re
import unicodedata

In [2]:
BASE_PATH = r"C:\ml 2026\dataset"

TRAIN_PATH = os.path.join(BASE_PATH, "train")
TEST_PATH = os.path.join(BASE_PATH, "test")

print("Train path:", TRAIN_PATH)
print("Test path:", TEST_PATH)

Train path: C:\ml 2026\dataset\train
Test path: C:\ml 2026\dataset\test

In [3]:
train_s1 = pd.read_csv(
    os.path.join(TRAIN_PATH, "train_source1.tsv"),
    sep="\t"
)

train_s2 = pd.read_csv(
    os.path.join(TRAIN_PATH, "train_source2.tsv"),
    sep="\t"
)

train_s3 = pd.read_csv(
    os.path.join(TRAIN_PATH, "train_source3.tsv"),
    sep="\t"
)

print("S1:", train_s1.shape)
print("S2:", train_s2.shape)
print("S3:", train_s3.shape)

S1: (2206821, 4)
S2: (5034616, 4)
S3: (5285603, 4)

In [4]:
print("S1 memory:", train_s1.memory_usage(deep=True).sum() / 1024**3, "GB")
print("S2 memory:", train_s2.memory_usage(deep=True).sum() / 1024**3, "GB")
print("S3 memory:", train_s3.memory_usage(deep=True).sum() / 1024**3, "GB")

total_memory = (
    train_s1.memory_usage(deep=True).sum()
    + train_s2.memory_usage(deep=True).sum()
    + train_s3.memory_usage(deep=True).sum()
)

print("Total memory:", total_memory / 1024**3, "GB")

S1 memory: 0.5902594346553087 GB
S2 memory: 1.385547123849392 GB
S3 memory: 1.4438208937644958 GB
Total memory: 3.4196274522691965 GB

In [5]:
print("SOURCE 1 NAMES")
display(train_s1[["business_name"]].head(20))

print("SOURCE 2 NAMES")
display(train_s2[["business_name"]].head(20))

print("SOURCE 3 NAMES")
display(train_s3[["business_name"]].head(20))

SOURCE 1 NAMES

                               business_name
0                        Orelee's Barbershop
1                                Prime Money
2                              B+ Retail Inc
3                              Christ Chapel
4                    Prabhav Business Center
5                 Custom Wealth Services LLC
6   Consulting Nyasa Nursing Private Limited
7                          Nexus Anchor Rain
8                          Moore Bitwise Inc
9                 Dermatology Green Medicine
10                        Crystal Lending PC
11                Dream Construction Limited
12                       Kelly Advisory, Inc
13                                    Helios
14                    Unified Choice Dynamix
15                Health Fellowship Partners
16          Smart Healthcare Private Limited
17                    Callicoat & Dailey Inc
18                             Iris Advisors
19         Secunderabad Park Private Limited

SOURCE 2 NAMES

                                        business_name
0                     राम मार्केटिंग प्राइवेट लिमिटेड
1                        -- Holloway Peak Inc Seafood
2                            आदित्य प्रॉपर्टीज एलएलपी
3                                          Summit Inc
4                        Delta Tetlecommunication Inc
5                                      Lee and Lawson
6   SHIVSHAKTI VIDYALAYA VIDYALAYA OVERSEAS CORPOR...
7                          Shree Infracon Private Ltd
8                        Chavira Platinum Chimera LLC
9            FOUNDATION EXCEL AGENCY PRIVATE  LIMITED
10                                   heassociates.com
11                   सन कंस्ट्रक्शंस प्राइवेट लिमिटेड
12         Global Developers Medicals Private Limited
13                       ASSET BUILDING COALITION LLC
14                  Olszewski Holding Company LLC LLC
15                                   CANDY'S-SERVICES
16                            रियल मॉडर्न फूड लिमिटेड
17                       Crestline Crestline Clean LP
18                                               Nion
19                       Keystone Odyssey Odyssey LLC

SOURCE 3 NAMES

                                  business_name
0                            wilfordhancock.com
1   International South Consultants Private Ltd
2                   LLC Moncada Léarning Center
3                                Moyna's Coffee
4                  Pvt. EFS Print Ventures Ltd.
5                LLC Hernandez Colonial Redwood
6                 Classic Equity Partners Group
7                Ectolumdrex dba X+ Madison Inc
8                       Animal Hanisch Hospirlg
9                                 Gomez Optimal
10             The Rapid  Learning Alliance LLC
11                   Indian Care Public Limited
12                                        Béque
13                            #centraleducation
14          அரிஹந்த் Foundation Private Limited
15                          Wildlife Guild  LLC
16                           Cinder Charlton-PC
17                               ZRO Trinity Co
18            Bajaj Foundation  Private Limited
19                            Estell's Creative

In [6]:
def normalize_text(text):
    if pd.isna(text):
        return ""

    text = str(text)

    text = unicodedata.normalize("NFKC", text)

    text = text.lower()

    text = text.strip()

    text = re.sub(r"\s+", " ", text)

    return text

In [7]:
examples = [
    "  Prime   Money  ",
    "Orelee's Barbershop",
    "B+ Retail Inc",
    "  Christ   Chapel  "
]

for x in examples:
    print("Original :", repr(x))
    print("Normalized:", repr(normalize_text(x)))
    print()

Original : '  Prime   Money  '
Normalized: 'prime money'

Original : "Orelee's Barbershop"
Normalized: "orelee's barbershop"

Original : 'B+ Retail Inc'
Normalized: 'b+ retail inc'

Original : '  Christ   Chapel  '
Normalized: 'christ chapel'

In [24]:
def normalize_alnum(text):
    text = normalize_text(text)

    chars = []
    for ch in text:
        if ch.isalnum() or ch.isspace():
            chars.append(ch)
        else:
            chars.append(" ")

    text = "".join(chars)
    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [25]:
def normalize_compact(text):
    text = normalize_text(text)

    text = re.sub(r"[^a-z0-9]+", "", text)

    return text
examples = [
    "B+ Retail Inc",
    "Orelee's Barbershop",
    "Delta-Telecommunication Inc."
]

for x in examples:
    print("Original :", x)
    print("Compact  :", normalize_compact(x))
    print()

Original : B+ Retail Inc
Compact  : bretailinc

Original : Orelee's Barbershop
Compact  : oreleesbarbershop

Original : Delta-Telecommunication Inc.
Compact  : deltatelecommunicationinc

In [26]:
train_s1["name_normalized"] = (
    train_s1["business_name"]
    .apply(normalize_text)
)

train_s1["name_alnum"] = (
    train_s1["business_name"]
    .apply(normalize_alnum)
)

train_s1["name_compact"] = (
    train_s1["business_name"]
    .apply(normalize_compact)
)

In [27]:
display(
    train_s1[
        [
            "business_name",
            "name_normalized",
            "name_alnum",
            "name_compact"
        ]
    ].head(30)
)

,business_name,name_normalized,name_alnum,name_compact
0,Orelee's Barbershop,orelee's barbershop,orelee s barbershop,oreleesbarbershop
1,Prime Money,prime money,prime money,primemoney
2,B+ Retail Inc,b+ retail inc,b retail inc,bretailinc
3,Christ Chapel,christ chapel,christ chapel,christchapel
4,Prabhav Business Center,prabhav business center,prabhav business center,prabhavbusinesscenter
5,Custom Wealth Services LLC,custom wealth services llc,custom wealth services llc,customwealthservicesllc
6,Consulting Nyasa Nursing Private Limited,consulting nyasa nursing private limited,consulting nyasa nursing private limited,consultingnyasanursingprivatelimited
7,Nexus Anchor Rain,nexus anchor rain,nexus anchor rain,nexusanchorrain
8,Moore Bitwise Inc,moore bitwise inc,moore bitwise inc,moorebitwiseinc
9,Dermatology Green Medicine,dermatology green medicine,dermatology green medicine,dermatologygreenmedicine
10,Crystal Lending PC,crystal lending pc,crystal lending pc,crystallendingpc
11,Dream Construction Limited,dream construction limited,dream construction limited,dreamconstructionlimited
12,"Kelly Advisory, Inc","kelly advisory, inc",kelly advisory inc,kellyadvisoryinc
13,Helios,helios,helios,helios
14,Unified Choice Dynamix,unified choice dynamix,unified choice dynamix,unifiedchoicedynamix
15,Health Fellowship Partners,health fellowship partners,health fellowship partners,healthfellowshippartners
16,Smart Healthcare Private Limited,smart healthcare private limited,smart healthcare private limited,smarthealthcareprivatelimited
17,Callicoat & Dailey Inc,callicoat & dailey inc,callicoat dailey inc,callicoatdaileyinc
18,Iris Advisors,iris advisors,iris advisors,irisadvisors
19,Secunderabad Park Private Limited,secunderabad park private limited,secunderabad park private limited,secunderabadparkprivatelimited
20,Holy Synagogue,holy synagogue,holy synagogue,holysynagogue
21,Green Logistics Private Limited,green logistics private limited,green logistics private limited,greenlogisticsprivatelimited
22,Scott Eagle Inc,scott eagle inc,scott eagle inc,scotteagleinc
23,Rajani Enterprises of Kannur,rajani enterprises of kannur,rajani enterprises of kannur,rajanienterprisesofkannur
24,"Schaefer, Michael and Silver Associates","schaefer, michael and silver associates",schaefer michael and silver associates,schaefermichaelandsilverassociates
25,Colline Molitor Sea LLC,colline molitor sea llc,colline molitor sea llc,collinemolitorseallc
26,"Aggie E. Nagle, L.C.S.W.","aggie e. nagle, l.c.s.w.",aggie e nagle l c s w,aggieenaglelcsw
27,Angad Multitrade Ltd,angad multitrade ltd,angad multitrade ltd,angadmultitradeltd
28,Global Hovnanian LLC,global hovnanian llc,global hovnanian llc,globalhovnanianllc
29,Pacific Learning Laboratories LLC,pacific learning laboratories llc,pacific learning laboratories llc,pacificlearninglaboratoriesllc

In [28]:
LEGAL_SUFFIXES = [
    "private limited",
    "pvt limited",
    "pvt ltd",
    "private ltd",
    "public limited",
    "public ltd",
    "limited liability company",
    "l l c",
    "llc",
    "incorporated",
    "inc",
    "corporation",
    "corp",
    "company",
    "co",
    "limited",
    "ltd",
    "llp",
    "pvt"
]

In [29]:
def normalize_name_no_suffix(text):
    text = normalize_alnum(text)

    if not text:
        return ""

    tokens = text.split()

    while tokens:
        current = " ".join(tokens[-3:])

        if current in LEGAL_SUFFIXES:
            tokens = tokens[:-3]
            continue

        current = " ".join(tokens[-2:])

        if current in LEGAL_SUFFIXES:
            tokens = tokens[:-2]
            continue

        current = tokens[-1]

        if current in LEGAL_SUFFIXES:
            tokens = tokens[:-1]
            continue

        break

    return " ".join(tokens)

In [30]:
examples = [
    "ABC Technologies Pvt Ltd",
    "ABC Technologies Private Limited",
    "ABC Technologies Pvt. Ltd.",
    "ABC Technologies Inc.",
    "ABC Technologies Corporation",
    "ABC Technologies LLC",
    "ABC Technologies"
]

for x in examples:
    print("Original :", x)
    print("No suffix:", normalize_name_no_suffix(x))
    print()

Original : ABC Technologies Pvt Ltd
No suffix: abc technologies

Original : ABC Technologies Private Limited
No suffix: abc technologies

Original : ABC Technologies Pvt. Ltd.
No suffix: abc technologies

Original : ABC Technologies Inc.
No suffix: abc technologies

Original : ABC Technologies Corporation
No suffix: abc technologies

Original : ABC Technologies LLC
No suffix: abc technologies

Original : ABC Technologies
No suffix: abc technologies

In [31]:
train_s1["name_no_suffix"] = (
    train_s1["business_name"]
    .apply(normalize_name_no_suffix)
)

In [32]:
display(
    train_s1[
        [
            "business_name",
            "name_normalized",
            "name_alnum",
            "name_no_suffix"
        ]
    ].head(30)
)

,business_name,name_normalized,name_alnum,name_no_suffix
0,Orelee's Barbershop,orelee's barbershop,orelee s barbershop,orelee s barbershop
1,Prime Money,prime money,prime money,prime money
2,B+ Retail Inc,b+ retail inc,b retail inc,b retail
3,Christ Chapel,christ chapel,christ chapel,christ chapel
4,Prabhav Business Center,prabhav business center,prabhav business center,prabhav business center
5,Custom Wealth Services LLC,custom wealth services llc,custom wealth services llc,custom wealth services
6,Consulting Nyasa Nursing Private Limited,consulting nyasa nursing private limited,consulting nyasa nursing private limited,consulting nyasa nursing
7,Nexus Anchor Rain,nexus anchor rain,nexus anchor rain,nexus anchor rain
8,Moore Bitwise Inc,moore bitwise inc,moore bitwise inc,moore bitwise
9,Dermatology Green Medicine,dermatology green medicine,dermatology green medicine,dermatology green medicine
10,Crystal Lending PC,crystal lending pc,crystal lending pc,crystal lending pc
11,Dream Construction Limited,dream construction limited,dream construction limited,dream construction
12,"Kelly Advisory, Inc","kelly advisory, inc",kelly advisory inc,kelly advisory
13,Helios,helios,helios,helios
14,Unified Choice Dynamix,unified choice dynamix,unified choice dynamix,unified choice dynamix
15,Health Fellowship Partners,health fellowship partners,health fellowship partners,health fellowship partners
16,Smart Healthcare Private Limited,smart healthcare private limited,smart healthcare private limited,smart healthcare
17,Callicoat & Dailey Inc,callicoat & dailey inc,callicoat dailey inc,callicoat dailey
18,Iris Advisors,iris advisors,iris advisors,iris advisors
19,Secunderabad Park Private Limited,secunderabad park private limited,secunderabad park private limited,secunderabad park
20,Holy Synagogue,holy synagogue,holy synagogue,holy synagogue
21,Green Logistics Private Limited,green logistics private limited,green logistics private limited,green logistics
22,Scott Eagle Inc,scott eagle inc,scott eagle inc,scott eagle
23,Rajani Enterprises of Kannur,rajani enterprises of kannur,rajani enterprises of kannur,rajani enterprises of kannur
24,"Schaefer, Michael and Silver Associates","schaefer, michael and silver associates",schaefer michael and silver associates,schaefer michael and silver associates
25,Colline Molitor Sea LLC,colline molitor sea llc,colline molitor sea llc,colline molitor sea
26,"Aggie E. Nagle, L.C.S.W.","aggie e. nagle, l.c.s.w.",aggie e nagle l c s w,aggie e nagle l c s w
27,Angad Multitrade Ltd,angad multitrade ltd,angad multitrade ltd,angad multitrade
28,Global Hovnanian LLC,global hovnanian llc,global hovnanian llc,global hovnanian
29,Pacific Learning Laboratories LLC,pacific learning laboratories llc,pacific learning laboratories llc,pacific learning laboratories

In [33]:
def normalize_name_ampersand(text):
    text = normalize_text(text)

    text = re.sub(r"\band\b", " & ", text)
    text = re.sub(r"\s*&\s*", " & ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [34]:
examples = [
    "Callicoat & Dailey Inc",
    "Callicoat and Dailey Inc",
    "Smith & Sons",
    "Smith and Sons"
]

for x in examples:
    print("Original :", x)
    print("Normalized:", normalize_name_ampersand(x))
    print()

Original : Callicoat & Dailey Inc
Normalized: callicoat & dailey inc

Original : Callicoat and Dailey Inc
Normalized: callicoat & dailey inc

Original : Smith & Sons
Normalized: smith & sons

Original : Smith and Sons
Normalized: smith & sons

In [35]:
train_s1["name_ampersand"] = (
    train_s1["business_name"]
    .apply(normalize_name_ampersand)
)

In [36]:
display(
    train_s1[
        train_s1["business_name"]
        .str.contains(r"&|\band\b", case=False, regex=True, na=False)
    ][
        [
            "business_name",
            "name_normalized",
            "name_ampersand"
        ]
    ].head(30)
)

,business_name,name_normalized,name_ampersand
17,Callicoat & Dailey Inc,callicoat & dailey inc,callicoat & dailey inc
24,"Schaefer, Michael and Silver Associates","schaefer, michael and silver associates","schaefer, michael & silver associates"
34,Foot & Ankle Allied Center LLC,foot & ankle allied center llc,foot & ankle allied center llc
44,Foot & Ankle Patriot Group,foot & ankle patriot group,foot & ankle patriot group
54,Abhushan & Brothers Co,abhushan & brothers co,abhushan & brothers co
65,Ear Nose & Throat Group of Oberlin,ear nose & throat group of oberlin,ear nose & throat group of oberlin
83,Hartman & Hoang LLC,hartman & hoang llc,hartman & hoang llc
96,"Pocius, Herrera & Lima Connecticut Inc","pocius, herrera & lima connecticut inc","pocius, herrera & lima connecticut inc"
97,Murray & Cruz Inc,murray & cruz inc,murray & cruz inc
101,U Q & Z Kimco,u q & z kimco,u q & z kimco
102,"Mobley, Haislip & Barr Vision Center, LLC","mobley, haislip & barr vision center, llc","mobley, haislip & barr vision center, llc"
110,Ramos and Benham Fusion,ramos and benham fusion,ramos & benham fusion
111,"Adams, Williams and Alexander Carolina LLC","adams, williams and alexander carolina llc","adams, williams & alexander carolina llc"
127,"Knox and Nicholas, Inc","knox and nicholas, inc","knox & nicholas, inc"
128,Doiron & Alvarez Token LLC,doiron & alvarez token llc,doiron & alvarez token llc
155,"Bermudez, Rice and Crittenden Inc","bermudez, rice and crittenden inc","bermudez, rice & crittenden inc"
194,D & L Metro LLC,d & l metro llc,d & l metro llc
196,"Allen, Sherpa & Lebowitz Superior LLC","allen, sherpa & lebowitz superior llc","allen, sherpa & lebowitz superior llc"
209,Namaskar & Co Company,namaskar & co company,namaskar & co company
227,Shorter and Reyes Xrp,shorter and reyes xrp,shorter & reyes xrp
245,"Buttler, Wilding and Manjarrez Inc","buttler, wilding and manjarrez inc","buttler, wilding & manjarrez inc"
260,Valley & Co,valley & co,valley & co
287,"Curatolo, Juergens and Arrington","curatolo, juergens and arrington","curatolo, juergens & arrington"
310,Surya & Brothers Pvt Ltd,surya & brothers pvt ltd,surya & brothers pvt ltd
316,High and Dills Generation LLC,high and dills generation llc,high & dills generation llc
330,Sector & Co of Noida,sector & co of noida,sector & co of noida
333,As & Sons Pvt Ltd,as & sons pvt ltd,as & sons pvt ltd
334,Webster & Mullins LLC,webster & mullins llc,webster & mullins llc
344,Ear Nose & Throat Tri-State Specialists Associ...,ear nose & throat tri-state specialists associ...,ear nose & throat tri-state specialists associ...
345,Pasillas and Rabinovich Group,pasillas and rabinovich group,pasillas & rabinovich group

In [37]:
test_names = [
    "राम मार्केटिंग प्राइवेट लिमिटेड",
    "Café de Paris",
    "Müller & Sons",
    "東京レストラン",
    "ABC Pvt. Ltd."
]

for x in test_names:
    print("Original :", x)
    print("Alnum    :", normalize_alnum(x))
    print()

Original : राम मार्केटिंग प्राइवेट लिमिटेड
Alnum    : र म म र क ट ग प र इव ट ल म ट ड

Original : Café de Paris
Alnum    : café de paris

Original : Müller & Sons
Alnum    : müller sons

Original : 東京レストラン
Alnum    : 東京レストラン

Original : ABC Pvt. Ltd.
Alnum    : abc pvt ltd

In [38]:
def normalize_address(text):
    if pd.isna(text):
        return ""

    text = normalize_text(text)

    # Replace punctuation with spaces
    chars = []
    for ch in text:
        if ch.isalnum() or ch.isspace():
            chars.append(ch)
        else:
            chars.append(" ")

    text = "".join(chars)
    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [39]:
address_examples = [
    "123 Main Street, Chennai",
    "123 Main St., Chennai",
    "Flat #4, MG Road, Bengaluru",
    "Near SBI ATM, 45 Gandhi Rd",
    "राम नगर, दिल्ली"
]

for x in address_examples:
    print("Original   :", x)
    print("Normalized :", normalize_address(x))
    print()

Original   : 123 Main Street, Chennai
Normalized : 123 main street chennai

Original   : 123 Main St., Chennai
Normalized : 123 main st chennai

Original   : Flat #4, MG Road, Bengaluru
Normalized : flat 4 mg road bengaluru

Original   : Near SBI ATM, 45 Gandhi Rd
Normalized : near sbi atm 45 gandhi rd

Original   : राम नगर, दिल्ली
Normalized : र म नगर द ल ल

In [40]:
ADDRESS_ABBREVIATIONS = {
    "rd": "road",
    "st": "street",
    "ave": "avenue",
    "av": "avenue",
    "blvd": "boulevard",
    "dr": "drive",
    "ln": "lane",
    "pkwy": "parkway",
    "hwy": "highway",
    "rdg": "ridge",
    "ct": "court",
    "pl": "place",
    "trl": "trail",
    "sq": "square"
}

In [42]:
def normalize_address_abbreviations(text):
    text = normalize_address(text)

    if not text:
        return ""

    tokens = text.split()

    tokens = [
        ADDRESS_ABBREVIATIONS.get(token, token)
        for token in tokens
    ]

    return " ".join(tokens)
address_examples = [
    "123 Main Rd",
    "123 Main Road",
    "45 MG St",
    "45 MG Street",
    "10 Park Ave",
    "10 Park Avenue"
]

for x in address_examples:
    print("Original   :", x)
    print("Normalized :", normalize_address_abbreviations(x))
    print()

Original   : 123 Main Rd
Normalized : 123 main road

Original   : 123 Main Road
Normalized : 123 main road

Original   : 45 MG St
Normalized : 45 mg street

Original   : 45 MG Street
Normalized : 45 mg street

Original   : 10 Park Ave
Normalized : 10 park avenue

Original   : 10 Park Avenue
Normalized : 10 park avenue

In [43]:
train_s1["address_normalized"] = (
    train_s1["business_address"]
    .apply(normalize_address)
)

train_s1["address_abbrev"] = (
    train_s1["business_address"]
    .apply(normalize_address_abbreviations)
)

In [44]:
display(
    train_s1[
        [
            "business_address",
            "address_normalized",
            "address_abbrev"
        ]
    ].head(30)
)

,business_address,address_normalized,address_abbrev
0,"1795 Westchester Drive, High Point, NC",1795 westchester drive high point nc,1795 westchester drive high point nc
1,"17560 Ellis Road, Tahlequah, OK",17560 ellis road tahlequah ok,17560 ellis road tahlequah ok
2,"1712 Montebello Avenue, Phoenix, AZ",1712 montebello avenue phoenix az,1712 montebello avenue phoenix az
3,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",2100 cameron drive unit apartment g dundalk md,2100 cameron drive unit apartment g dundalk md
4,"797, Lake Town Block A, Kolkata, Howrah, West ...",797 lake town block a kolkata howrah west bengal,797 lake town block a kolkata howrah west bengal
5,"OH, Columbus, 5559 Orville Avenue",oh columbus 5559 orville avenue,oh columbus 5559 orville avenue
6,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",2505 tower 1 oakwood runwal greens mulund gore...,2505 tower 1 oakwood runwal greens mulund gore...
7,"1111 Church Street, Unit 2007, Nashville, TN",1111 church street unit 2007 nashville tn,1111 church street unit 2007 nashville tn
8,"337 Oakland Avenue, Michigan City, IN",337 oakland avenue michigan city in,337 oakland avenue michigan city in
9,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",294 meadowcreek drive unit unit 2 village of p...,294 meadowcreek drive unit unit 2 village of p...
10,"11643 Prosperity Road, South Jordan, UT",11643 prosperity road south jordan ut,11643 prosperity road south jordan ut
11,"H.No.16-11-23/37/A, 2Nd Floor, Flat No.207, Sa...",h no 16 11 23 37 a 2nd floor flat no 207 sagar...,h no 16 11 23 37 a 2nd floor flat no 207 sagar...
12,"301 1st Street, Chokio, MN",301 1st street chokio mn,301 1st street chokio mn
13,"66 Edgewood Street, Bridgeport, CT",66 edgewood street bridgeport ct,66 edgewood street bridgeport court
14,"Unit BUILDING 3030, MD, 2701 Eastern Boulevard...",unit building 3030 md 2701 eastern boulevard m...,unit building 3030 md 2701 eastern boulevard m...
15,"601 Oleander Circle, Virginia Beach City, VA",601 oleander circle virginia beach city va,601 oleander circle virginia beach city va
16,"303, 3Rd Floor Sakar 5 B/H Natraj Cinema Ashra...",303 3rd floor sakar 5 b h natraj cinema ashram...,303 3rd floor sakar 5 b h natraj cinema ashram...
17,"Charlotte, NC, 833 Reliance Street",charlotte nc 833 reliance street,charlotte nc 833 reliance street
18,House No-777 Raghubir Bhawanmadan Pur Khadar S...,house no 777 raghubir bhawanmadan pur khadar s...,house no 777 raghubir bhawanmadan pur khadar s...
19,"Secunderabad, Hyderabad, Plot No.53, Flat No.4...",secunderabad hyderabad plot no 53 flat no 402 ...,secunderabad hyderabad plot no 53 flat no 402 ...
20,"Sapulpa, OK, 2204 Park Street",sapulpa ok 2204 park street,sapulpa ok 2204 park street
21,"E-7, Second Floor, New Delhi, South Delhi, Delhi",e 7 second floor new delhi south delhi delhi,e 7 second floor new delhi south delhi delhi
22,"4828 Hedges Avenue, Kansas City, MO",4828 hedges avenue kansas city mo,4828 hedges avenue kansas city mo
23,"46/1106, Dhanalakshmi Road, Near Amani Auditor...",46 1106 dhanalakshmi road near amani auditoriu...,46 1106 dhanalakshmi road near amani auditoriu...
24,"32876 Circle Drive, Millsboro, DE",32876 circle drive millsboro de,32876 circle drive millsboro de
25,"5620 Trinity Road, Unit 103, Raleigh, NC",5620 trinity road unit 103 raleigh nc,5620 trinity road unit 103 raleigh nc
26,"11900 54th Avenue, Plymouth, MN",11900 54th avenue plymouth mn,11900 54th avenue plymouth mn
27,"Building No. 37/4, First Floor Opp Bharata Mat...",building no 37 4 first floor opp bharata mata ...,building no 37 4 first floor opp bharata mata ...
28,"4024 39th Avenue, Seattle, WA",4024 39th avenue seattle wa,4024 39th avenue seattle wa
29,"4810 Nassau Avenue, Sand Springs, OK",4810 nassau avenue sand springs ok,4810 nassau avenue sand springs ok

In [45]:
POSTAL_PATTERN = re.compile(r"\b\d{5,6}\b")

def extract_postal_code(text):
    if pd.isna(text):
        return ""

    text = normalize_text(text)

    match = POSTAL_PATTERN.search(text)

    if match:
        return match.group(0)

    return ""

In [46]:
address_examples = [
    "123 Main Street, Chennai 600001",
    "45 MG Road, Bengaluru 560001",
    "New York NY 10001",
    "No postal code here"
]

for x in address_examples:
    print("Address :", x)
    print("Postal  :", extract_postal_code(x))
    print()

Address : 123 Main Street, Chennai 600001
Postal  : 600001

Address : 45 MG Road, Bengaluru 560001
Postal  : 560001

Address : New York NY 10001
Postal  : 10001

Address : No postal code here
Postal  :

In [47]:
train_s1["postal_code"] = (
    train_s1["business_address"]
    .apply(extract_postal_code)
)

In [48]:
display(
    train_s1[
        [
            "business_address",
            "address_normalized",
            "address_abbrev",
            "postal_code"
        ]
    ].head(30)
)

,business_address,address_normalized,address_abbrev,postal_code
0,"1795 Westchester Drive, High Point, NC",1795 westchester drive high point nc,1795 westchester drive high point nc,
1,"17560 Ellis Road, Tahlequah, OK",17560 ellis road tahlequah ok,17560 ellis road tahlequah ok,17560
2,"1712 Montebello Avenue, Phoenix, AZ",1712 montebello avenue phoenix az,1712 montebello avenue phoenix az,
3,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",2100 cameron drive unit apartment g dundalk md,2100 cameron drive unit apartment g dundalk md,
4,"797, Lake Town Block A, Kolkata, Howrah, West ...",797 lake town block a kolkata howrah west bengal,797 lake town block a kolkata howrah west bengal,
5,"OH, Columbus, 5559 Orville Avenue",oh columbus 5559 orville avenue,oh columbus 5559 orville avenue,
6,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",2505 tower 1 oakwood runwal greens mulund gore...,2505 tower 1 oakwood runwal greens mulund gore...,
7,"1111 Church Street, Unit 2007, Nashville, TN",1111 church street unit 2007 nashville tn,1111 church street unit 2007 nashville tn,
8,"337 Oakland Avenue, Michigan City, IN",337 oakland avenue michigan city in,337 oakland avenue michigan city in,
9,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",294 meadowcreek drive unit unit 2 village of p...,294 meadowcreek drive unit unit 2 village of p...,
10,"11643 Prosperity Road, South Jordan, UT",11643 prosperity road south jordan ut,11643 prosperity road south jordan ut,11643
11,"H.No.16-11-23/37/A, 2Nd Floor, Flat No.207, Sa...",h no 16 11 23 37 a 2nd floor flat no 207 sagar...,h no 16 11 23 37 a 2nd floor flat no 207 sagar...,
12,"301 1st Street, Chokio, MN",301 1st street chokio mn,301 1st street chokio mn,
13,"66 Edgewood Street, Bridgeport, CT",66 edgewood street bridgeport ct,66 edgewood street bridgeport court,
14,"Unit BUILDING 3030, MD, 2701 Eastern Boulevard...",unit building 3030 md 2701 eastern boulevard m...,unit building 3030 md 2701 eastern boulevard m...,
15,"601 Oleander Circle, Virginia Beach City, VA",601 oleander circle virginia beach city va,601 oleander circle virginia beach city va,
16,"303, 3Rd Floor Sakar 5 B/H Natraj Cinema Ashra...",303 3rd floor sakar 5 b h natraj cinema ashram...,303 3rd floor sakar 5 b h natraj cinema ashram...,
17,"Charlotte, NC, 833 Reliance Street",charlotte nc 833 reliance street,charlotte nc 833 reliance street,
18,House No-777 Raghubir Bhawanmadan Pur Khadar S...,house no 777 raghubir bhawanmadan pur khadar s...,house no 777 raghubir bhawanmadan pur khadar s...,
19,"Secunderabad, Hyderabad, Plot No.53, Flat No.4...",secunderabad hyderabad plot no 53 flat no 402 ...,secunderabad hyderabad plot no 53 flat no 402 ...,
20,"Sapulpa, OK, 2204 Park Street",sapulpa ok 2204 park street,sapulpa ok 2204 park street,
21,"E-7, Second Floor, New Delhi, South Delhi, Delhi",e 7 second floor new delhi south delhi delhi,e 7 second floor new delhi south delhi delhi,
22,"4828 Hedges Avenue, Kansas City, MO",4828 hedges avenue kansas city mo,4828 hedges avenue kansas city mo,
23,"46/1106, Dhanalakshmi Road, Near Amani Auditor...",46 1106 dhanalakshmi road near amani auditoriu...,46 1106 dhanalakshmi road near amani auditoriu...,
24,"32876 Circle Drive, Millsboro, DE",32876 circle drive millsboro de,32876 circle drive millsboro de,32876
25,"5620 Trinity Road, Unit 103, Raleigh, NC",5620 trinity road unit 103 raleigh nc,5620 trinity road unit 103 raleigh nc,
26,"11900 54th Avenue, Plymouth, MN",11900 54th avenue plymouth mn,11900 54th avenue plymouth mn,11900
27,"Building No. 37/4, First Floor Opp Bharata Mat...",building no 37 4 first floor opp bharata mata ...,building no 37 4 first floor opp bharata mata ...,
28,"4024 39th Avenue, Seattle, WA",4024 39th avenue seattle wa,4024 39th avenue seattle wa,
29,"4810 Nassau Avenue, Sand Springs, OK",4810 nassau avenue sand springs ok,4810 nassau avenue sand springs ok,

In [49]:
def normalize_address_tokens(text):
    text = normalize_address_abbreviations(text)

    if not text:
        return ""

    tokens = text.split()

    tokens = sorted(set(tokens))

    return " ".join(tokens)

In [50]:
address_examples = [
    "12 MG Road Chennai",
    "Chennai MG Road 12",
    "45 Main Street New York",
    "New York 45 Main Street",
    "600001 Chennai MG Road"
]

for x in address_examples:
    print("Original :", x)
    print("Tokens   :", normalize_address_tokens(x))
    print()

Original : 12 MG Road Chennai
Tokens   : 12 chennai mg road

Original : Chennai MG Road 12
Tokens   : 12 chennai mg road

Original : 45 Main Street New York
Tokens   : 45 main new street york

Original : New York 45 Main Street
Tokens   : 45 main new street york

Original : 600001 Chennai MG Road
Tokens   : 600001 chennai mg road

In [51]:
train_s1["address_tokens"] = (
    train_s1["business_address"]
    .apply(normalize_address_tokens)
)

In [52]:
display(
    train_s1[
        [
            "business_address",
            "address_normalized",
            "address_abbrev",
            "postal_code",
            "address_tokens"
        ]
    ].head(30)
)

,business_address,address_normalized,address_abbrev,postal_code,address_tokens
0,"1795 Westchester Drive, High Point, NC",1795 westchester drive high point nc,1795 westchester drive high point nc,,1795 drive high nc point westchester
1,"17560 Ellis Road, Tahlequah, OK",17560 ellis road tahlequah ok,17560 ellis road tahlequah ok,17560,17560 ellis ok road tahlequah
2,"1712 Montebello Avenue, Phoenix, AZ",1712 montebello avenue phoenix az,1712 montebello avenue phoenix az,,1712 avenue az montebello phoenix
3,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",2100 cameron drive unit apartment g dundalk md,2100 cameron drive unit apartment g dundalk md,,2100 apartment cameron drive dundalk g md unit
4,"797, Lake Town Block A, Kolkata, Howrah, West ...",797 lake town block a kolkata howrah west bengal,797 lake town block a kolkata howrah west bengal,,797 a bengal block howrah kolkata lake town west
5,"OH, Columbus, 5559 Orville Avenue",oh columbus 5559 orville avenue,oh columbus 5559 orville avenue,,5559 avenue columbus oh orville
6,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",2505 tower 1 oakwood runwal greens mulund gore...,2505 tower 1 oakwood runwal greens mulund gore...,,1 2505 bhandup fortis goreagon greens hospital...
7,"1111 Church Street, Unit 2007, Nashville, TN",1111 church street unit 2007 nashville tn,1111 church street unit 2007 nashville tn,,1111 2007 church nashville street tn unit
8,"337 Oakland Avenue, Michigan City, IN",337 oakland avenue michigan city in,337 oakland avenue michigan city in,,337 avenue city in michigan oakland
9,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",294 meadowcreek drive unit unit 2 village of p...,294 meadowcreek drive unit unit 2 village of p...,,2 294 drive meadowcreek of pewaukee unit villa...
10,"11643 Prosperity Road, South Jordan, UT",11643 prosperity road south jordan ut,11643 prosperity road south jordan ut,11643,11643 jordan prosperity road south ut
11,"H.No.16-11-23/37/A, 2Nd Floor, Flat No.207, Sa...",h no 16 11 23 37 a 2nd floor flat no 207 sagar...,h no 16 11 23 37 a 2nd floor flat no 207 sagar...,,11 16 207 23 2nd 37 a building flat floor h ho...
12,"301 1st Street, Chokio, MN",301 1st street chokio mn,301 1st street chokio mn,,1st 301 chokio mn street
13,"66 Edgewood Street, Bridgeport, CT",66 edgewood street bridgeport ct,66 edgewood street bridgeport court,,66 bridgeport court edgewood street
14,"Unit BUILDING 3030, MD, 2701 Eastern Boulevard...",unit building 3030 md 2701 eastern boulevard m...,unit building 3030 md 2701 eastern boulevard m...,,2701 3030 boulevard building eastern md middle...
15,"601 Oleander Circle, Virginia Beach City, VA",601 oleander circle virginia beach city va,601 oleander circle virginia beach city va,,601 beach circle city oleander va virginia
16,"303, 3Rd Floor Sakar 5 B/H Natraj Cinema Ashra...",303 3rd floor sakar 5 b h natraj cinema ashram...,303 3rd floor sakar 5 b h natraj cinema ashram...,,303 3rd 5 ahmedabad ashram b cinema floor guja...
17,"Charlotte, NC, 833 Reliance Street",charlotte nc 833 reliance street,charlotte nc 833 reliance street,,833 charlotte nc reliance street
18,House No-777 Raghubir Bhawanmadan Pur Khadar S...,house no 777 raghubir bhawanmadan pur khadar s...,house no 777 raghubir bhawanmadan pur khadar s...,,777 bhawanmadan delhi house khadar no pur ragh...
19,"Secunderabad, Hyderabad, Plot No.53, Flat No.4...",secunderabad hyderabad plot no 53 flat no 402 ...,secunderabad hyderabad plot no 53 flat no 402 ...,,1 402 53 ammuguda colony estate flat hyderabad...
20,"Sapulpa, OK, 2204 Park Street",sapulpa ok 2204 park street,sapulpa ok 2204 park street,,2204 ok park sapulpa street
21,"E-7, Second Floor, New Delhi, South Delhi, Delhi",e 7 second floor new delhi south delhi delhi,e 7 second floor new delhi south delhi delhi,,7 delhi e floor new second south
22,"4828 Hedges Avenue, Kansas City, MO",4828 hedges avenue kansas city mo,4828 hedges avenue kansas city mo,,4828 avenue city hedges kansas mo
23,"46/1106, Dhanalakshmi Road, Near Amani Auditor...",46 1106 dhanalakshmi road near amani auditoriu...,46 1106 dhanalakshmi road near amani auditoriu...,,1106 46 amani auditorium dhanalakshmi kannur k...
24,"32876 Circle Drive, Millsboro, DE",32876 circle drive millsboro de,32876 circle drive millsboro de,32876,32876 circle de drive millsboro
25,"5620 Trinity Road, Unit 103, Raleigh, NC",5620 trinity road unit 103 raleigh nc,5620 trinity road unit 103 raleigh nc,,103 5620 nc raleigh road trinity unit
26,"11900 54th Avenue, Plymouth, MN",11900 54th avenue plymouth mn,11900 54th avenue plymouth mn,11900,11900 54th avenue mn plymouth
27,"Building No. 37/4, First Floor Opp Bharata Mat...",building no 37 4 first floor opp bharata mata ...,building no 37 4 first floor opp bharata mata ...,,37 4 bharata building college ernakulam first ...
28,"4024 39th Avenue, Seattle, WA",4024 39th avenue seattle wa,4024 39th avenue seattle wa,,39th 4024 avenue seattle wa
29,"4810 Nassau Avenue, Sand Springs, OK",4810 nassau avenue sand springs ok,4810 nassau avenue sand springs ok,,4810 avenue nassau ok sand springs

In [53]:
def add_name_normalizations(df):
    df["name_normalized"] = df["business_name"].apply(normalize_text)
    df["name_alnum"] = df["business_name"].apply(normalize_alnum)
    df["name_compact"] = df["business_name"].apply(normalize_compact)
    df["name_no_suffix"] = df["business_name"].apply(normalize_name_no_suffix)
    df["name_ampersand"] = df["business_name"].apply(normalize_name_ampersand)

    return df

In [54]:
def add_address_normalizations(df):
    df["address_normalized"] = df["business_address"].apply(normalize_address)
    df["address_abbrev"] = df["business_address"].apply(normalize_address_abbreviations)
    df["postal_code"] = df["business_address"].apply(extract_postal_code)
    df["address_tokens"] = df["business_address"].apply(normalize_address_tokens)

    return df

In [55]:
train_s2 = add_name_normalizations(train_s2)
train_s2 = add_address_normalizations(train_s2)

print("S2 normalization complete")

S2 normalization complete

In [56]:
train_s3 = add_name_normalizations(train_s3)
train_s3 = add_address_normalizations(train_s3)

print("S3 normalization complete")

S3 normalization complete

In [57]:
train_gt = pd.read_csv(
    os.path.join(TRAIN_PATH, "train_ground_truth.tsv"),
    sep="\t"
)

train_gt["matched_entity_ids"] = (
    train_gt["matched_entity_ids"]
    .fillna("")
)

train_gt["matched_list"] = (
    train_gt["matched_entity_ids"]
    .apply(
        lambda x: x.split(",") if x else []
    )
)

train_gt["match_count"] = (
    train_gt["matched_list"].str.len()
)

display(
    train_gt[
        [
            "source1_entity_id",
            "matched_entity_ids",
            "match_count"
        ]
    ].head(20)
)

,source1_entity_id,matched_entity_ids,match_count
0,S1-965667,"S2-681193310,S2-743505751,S3-775321672,S3-1129...",5
1,S1-55344266,"S2-249013014,S2-197070651,S3-478195123,S3-3843...",4
2,S1-343815751,"S2-790675320,S2-479876582,S3-878454467",3
3,S1-656753428,"S2-153058913,S2-24659151,S3-679606215",3
4,S1-102811957,"S2-478959098,S2-553508714,S2-625774905,S3-7280...",6
5,S1-18727616,"S2-755677256,S3-187831601,S3-641489370,S3-4762...",4
6,S1-318373630,"S2-660036492,S3-804600254",2
7,S1-86989137,"S3-274817120,S3-312496301",2
8,S1-29845983,"S2-648035184,S3-588502663",2
9,S1-789009573,"S2-383871912,S3-74481402,S3-576451439",3
10,S1-730934468,"S2-356983532,S3-352439310",2
11,S1-7293388,"S2-7028416,S2-442723188,S2-157073701,S3-523120965",4
12,S1-546142636,"S2-487600131,S2-582477216,S2-392804085,S3-2000...",6
13,S1-274126313,"S2-736616474,S2-680265918,S2-51486805,S3-92563...",6
14,S1-145361722,"S2-120366543,S2-939389287,S3-96572514",3
15,S1-503957000,"S2-994658326,S2-235117490,S2-353308450,S2-1732...",7
16,S1-692000596,"S2-580419223,S3-164220452",2
17,S1-561341312,"S2-483615364,S3-619529814",2
18,S1-777597828,"S2-836452886,S3-413669121",2
19,S1-282467635,"S2-938895481,S3-138350041",2